id = "iceicebergy"
name = "Ice Ice Bergy Theme"
version = "0.3.14"
schema_version = 1
description = "Turn off the lights and I'll glow"
repository = "https://github.com/jmsdnns/iceicebergy-zed-theme"
authors = ["Jms Dnns <jdennis@gmail.com>"]
themes = ["themes/iceicebergy.json"]
languages = []

[lib]

[grammars]

[language_servers]

[slash_commands]

[indexed_docs_providers]
